site_name: SS220 Developer Documentation
repo_url: https://github.com/SerbiaStrong-220/space-station-14
repo_name: SerbiaStrong-220/space-station-14
copyright: Copyright &copy; 2023 SS220. Written and maintained by TheArturZh.

theme:
    name: material
    language: ru
    palette:
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode

    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.sections

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/ss220

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

nav:
  - Главная: index.md
  - Сборка и запуск локального сервера: localhost.md
  - Диздоки:
    - Исследователи с Сиерры(Infinity):
      - disdocs/sierra/index.md
      - disdocs/sierra/backstory-gen.md
      - disdocs/sierra/planet-gen.md
  - Маппинг:
    - Обучение:
      - mapping/general.md
      - mapping/commands.md
      - mapping/controls.md
      - mapping/render.md
      - mapping/testing.md
      - mapping/checklist.md
      - Моя первая станция:
        - Этап 1 - Проектирование:
          - mapping/1station/part1/idea.md # Идея, вдохновение
          - mapping/1station/part1/schematic.md # Чертежи
          - mapping/1station/part1/dd.md # Дизайн-Документ 
        - Этап 2 - Маппинг:
          - mapping/1station/part2/preparation.md
          - Отделы:
            - mapping/1station/part2/general.md # Общее
            - mapping/1station/part2/service.md # Сервис
            - mapping/1station/part2/medical.md # Мед
            - mapping/1station/part2/eng.md # Инженерный
            - mapping/1station/part2/rnd.md # Научный
            - mapping/1station/part2/security.md # Охранный
            - mapping/1station/part2/dia.md # ДВД
            - mapping/1station/part2/command.md # Командный
            - mapping/1station/part2/techs.md # Технические/Секретки
        - Этап 3 - Инфраструктура:
          - mapping/1station/part3/lights.md # свет
          - mapping/1station/part3/energetic.md # всё об электричестве
          - mapping/1station/part3/atmos.md # всё об атмосе
          - mapping/1station/part3/utilisation.md # всё о трубах мусора
          - mapping/1station/part3/mailPosts.md # всё о почте
          - mapping/1station/part3/cameras.md # всё о камерах
          - mapping/1station/part3/warppoints.md # всё о маяках и варпах
          - mapping/1station/part3/wallmounts.md # настенные предметы
          - mapping/1station/part3/spawners.md # всё о спавнерах
        - Этап 4 - Релизная подготовка:
          - mapping/1station/part4/prototype-station.md #
          - mapping/1station/part4/worktest.md #
          - mapping/1station/part4/parallaxes.md #
          - mapping/1station/part4/camera-viewable-maps.md #
    - Наши работы:
      - Открытые диздоки:
        - mapping/dd/frankenstein.md
        - mapping/dd/axioma.md
        - mapping/dd/eclipse.md
        - mapping/dd/donuts.md
        - mapping/dd/frankenstein.md
  - Разработка:
    - development/dev-introduction.md
    - development/ecs.md
    - development/creating-simple-system.md